export const ADD_ESTUDIANTE = 'ADD_ESTUDIANTE';
export const ADD_GRUPO = 'ADD_GRUPO';

export const REMOVE_ESTUDIANTE = 'REMOVE_ESTUDIANTE';
export const REMOVE_GRUPO = 'REMOVE_GRUPO';

export const UPDATE_ESTUDIANTE = 'UPDATE_ESTUDIANTE';
export const UPDATE_GRUPO = 'UPDATE_GRUPO';

export const DETAILS_ESTUDIANTE = 'DETAILS_ESTUDIANTE';
export const DETAILS_GRUPO = 'DETAILS_GRUPO';



export const LOAD_ESTUDIANTES = 'LOAD_ESTUDIANTES';
export const LOAD_GRUPOS = 'LOAD_GRUPOS';

export const EDITAR_ESTUDIANTE = 'EDITAR_ESTUDIANTE';
export const EDITAR_GRUPO = 'EDITAR_GRUPO';

export const LOAD_CIUDADES = 'LOAD_CIUDADES';
export const LOAD_PROFESORES = 'LOAD_PROFESORES';